# Generated by Django 5.1.3 on 2024-12-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadModel',
        ),
    ]
